
version: 2

models:
    - name: example_model
      description: "A starter dbt model"
      columns:
          - name: total_users
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: filtered_users
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
